services:
  app:
    build:
      context: .
      target: base
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
  school_test_task_database_pg15:
    container_name: school_test_task_database
    image: postgres:15.5-alpine3.19
    command: postgres -p 5432 -c 'max_connections=200'
    env_file: 
      - .env.development
    expose:
      - "5432"
    volumes:
      - school_test_task-localpg-data:/var/lib/postgresql15/data
  chrome:
    container_name: rspec-chrome
    image: seleniarm/standalone-chromium
    ports:
      - 4444:4444
      - 7900:7900
      - 5900:5900

volumes:
  school_test_task-localpg-data:

networks:
  default:
    name: school_test_task
    external: true